@host = http://localhost:6000

### Register User
POST {{host}}/api/auth/register
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "admin12345",
    "account": {
        "name": "LE1896",
        "startingBalance": 100000
    }
}

### Login User
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "email": "user1@gmail.com",
    "password": "admin12345"
}